name: Customer Backend CI Workflow

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: sidi
          POSTGRES_PASSWORD: sidiba1994
          POSTGRES_DB: amigos
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses:  actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: run unit and integration test
        run: mvn -ntp -B clean verify